# Generated by Django 5.1.4 on 2025-06-09 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='api.rating'),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('fandom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='api.fandom')),
            ],
        ),
        migrations.CreateModel(
            name='WorkCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.character')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.work')),
            ],
            options={
                'unique_together': {('work', 'character')},
            },
        ),
    ]
